/** Canonical entry for collection API operations. */
export { collectionsService } from './collections.impl';
export type {
  BatchReminderResult,
  CollectionDisputeRecord,
  CollectionHoldRecord,
  CollectionLedgerRecord,
  CollectionListMeta,
  CollectionListOptions,
  CollectionListResult,
  CollectionMilestoneRecord,
  CollectionOverdueRecord,
  CollectionPromiseRecord,
  CollectionSummary,
  CollectionWorkbenchBundle,
  OriginalPaymentFacts,
  PaymentReversalReason,
  PaymentReversalDecision,
  PaymentReversalRequestReceipt,
  PaymentReversalReviewReceipt,
  PaymentReversalRequestRecord,
  PaymentReversalOrderSnapshot,
  PaymentReversalHistory,
  PaymentReversalResult,
} from './collections.impl';
