export const openApiSchemas = {
  PaginationMeta: {
    type: 'object',
    properties: {
      page: { type: 'integer', minimum: 1 },
      pageSize: { type: 'integer', minimum: 1, maximum: 100 },
      total: { type: 'integer', minimum: 0 },
      totalPages: { type: 'integer', minimum: 0 },
    },
  },
  CustomerListItem: {
    type: 'object',
    required: ['id', 'name', 'status', 'riskLevel'],
    properties: {
      id: { type: 'integer' },
      name: { type: 'string' },
      displayName: { type: 'string', nullable: true },
      nameZh: { type: 'string', nullable: true },
      nameEn: { type: 'string', nullable: true },
      nameVi: { type: 'string', nullable: true },
      contactName: { type: 'string', nullable: true },
      contactPhone: { type: 'string', nullable: true },
      contactEmail: { type: 'string', nullable: true },
      segment: { type: 'string', nullable: true, enum: ['direct', 'channel', 'mixed', null] },
      status: { type: 'string' },
      riskLevel: { type: 'string' },
      poolState: { type: 'string', nullable: true },
      salespersonId: { type: 'integer', nullable: true },
      creditLimit: { type: 'number', nullable: true },
      overdueAmount: { type: 'number', nullable: true },
      statistics: { type: 'object', additionalProperties: true },
    },
  },
  CustomerListResponse: {
    allOf: [
      { $ref: '#/components/schemas/ApiResponse' },
      {
        type: 'object',
        properties: {
          data: { type: 'array', items: { $ref: '#/components/schemas/CustomerListItem' } },
          meta: { $ref: '#/components/schemas/PaginationMeta' },
        },
      },
    ],
  },
  OrderListItem: {
    type: 'object',
    required: ['id', 'orderNo', 'customerId', 'customerName', 'status', 'paymentStatus'],
    properties: {
      id: { type: 'integer' },
      orderNo: { type: 'string' },
      customerId: { type: 'integer' },
      customerName: { type: 'string' },
      customerNameZh: { type: 'string', nullable: true },
      customerNameEn: { type: 'string', nullable: true },
      customerNameVi: { type: 'string', nullable: true },
      status: { type: 'string' },
      paymentStatus: { type: 'string' },
      financialStatus: { type: 'string', nullable: true },
      fulfillmentStatus: { type: 'string', nullable: true },
      finalAmount: { type: 'number' },
      paidAmount: { type: 'number' },
      outstandingAmount: { type: 'number' },
      currency: { type: 'string' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
  },
  OrderListResponse: {
    allOf: [
      { $ref: '#/components/schemas/ApiResponse' },
      {
        type: 'object',
        properties: {
          data: { type: 'array', items: { $ref: '#/components/schemas/OrderListItem' } },
          meta: { $ref: '#/components/schemas/PaginationMeta' },
        },
      },
    ],
  },
  CollectionOverdueListItem: {
    type: 'object',
    required: ['orderId', 'orderNo', 'customerId', 'customerName', 'dueDate', 'daysOverdue', 'outstanding', 'paymentStatus', 'level', 'label', 'nextAction'],
    properties: {
      orderId: { type: 'integer' },
      orderNo: { type: 'string' },
      dueDate: { type: 'string', format: 'date-time' },
      daysOverdue: { type: 'integer', minimum: 0 },
      level: { type: 'integer', minimum: 1 },
      label: { type: 'string' },
      nextAction: { type: 'string' },
      channel: { type: 'string' },
      holdRecommended: { type: 'boolean' },
      outstanding: { type: 'number' },
      finalAmount: { type: 'number' },
      paidAmount: { type: 'number' },
      receivableAdjustmentAmount: { type: 'number' },
      paymentStatus: { type: 'string' },
      customerId: { type: 'integer' },
      customerName: { type: 'string' },
      customerNameZh: { type: 'string', nullable: true },
      customerNameEn: { type: 'string', nullable: true },
      customerNameVi: { type: 'string', nullable: true },
      customerDisplayName: { type: 'string', nullable: true },
      contactName: { type: 'string', nullable: true },
      contactPhone: { type: 'string', nullable: true },
      ownerName: { type: 'string' },
      riskLevel: { type: 'string' },
      overdueAmount: { type: 'number' },
      collectionsStatus: { type: 'string' },
      dunningLevel: { type: 'integer', minimum: 0 },
      nextActionAt: { type: 'string', format: 'date-time', nullable: true },
      reminderCount: { type: 'integer', minimum: 0 },
      lastReminderAt: { type: 'string', format: 'date-time', nullable: true },
      contractNo: { type: 'string', nullable: true },
      contractTitle: { type: 'string', nullable: true },
    },
  },
  CollectionOverdueListResponse: {
    allOf: [
      { $ref: '#/components/schemas/ApiResponse' },
      {
        type: 'object',
        properties: {
          data: { type: 'array', items: { $ref: '#/components/schemas/CollectionOverdueListItem' } },
          meta: { $ref: '#/components/schemas/PaginationMeta' },
        },
      },
    ],
  },
  AIAssistRequest: {
    type: 'object',
    additionalProperties: false,
    required: ['prompt'],
    properties: {
      prompt: { type: 'string', minLength: 1, maxLength: 2000 },
      language: { type: 'string', enum: ['zh-CN', 'en-US', 'vi-VN'] },
      currentPage: { type: 'string', maxLength: 120 },
      visibleCounts: {
        type: 'object',
        deprecated: true,
        description: 'Compatibility-only client hint. The server ignores this field and never forwards it to an external AI provider.',
        additionalProperties: { type: 'integer', minimum: 0, maximum: 1000000 },
      },
    },
  },
  AIAssistResponse: {
    allOf: [
      { $ref: '#/components/schemas/ApiResponse' },
      {
        type: 'object',
        properties: {
          data: {
            type: 'object',
            required: ['answer', 'mode'],
            properties: {
              answer: { type: 'string', maxLength: 4000 },
              mode: { type: 'string', enum: ['local', 'external'] },
              reason: { type: 'string', enum: ['disabled', 'sensitive', 'unconfigured', 'provider_error', 'audit_unavailable', 'unsafe_output', 'response_too_large', 'budget_unconfigured', 'budget_store_unavailable', 'budget_exhausted', 'circuit_open'] },
            },
          },
        },
      },
    ],
  },
  WarehouseRequestId: {
    type: 'string',
    minLength: 1,
    maxLength: 80,
    pattern: '^[A-Za-z0-9][A-Za-z0-9._:-]{0,79}$',
    description: 'Caller-generated idempotency key. An exact retry is accepted; reuse with a different payload is rejected.',
  },
  WarehouseStockAdjustmentRequest: {
    type: 'object',
    additionalProperties: false,
    required: ['quantity', 'expectedQuantity', 'requestId'],
    properties: {
      quantity: { type: 'number', minimum: 0, description: 'Requested absolute quantity after adjustment.' },
      expectedQuantity: { type: 'number', minimum: 0, description: 'Quantity last read by the caller. A stale value returns HTTP 409.' },
      requestId: { $ref: '#/components/schemas/WarehouseRequestId' },
      note: { type: 'string', maxLength: 500 },
    },
  },
  WarehouseStockTransferRequest: {
    type: 'object',
    additionalProperties: false,
    required: ['toLocationId', 'quantity', 'requestId'],
    properties: {
      toLocationId: { type: 'integer', minimum: 1 },
      quantity: { type: 'number', exclusiveMinimum: 0 },
      requestId: { $ref: '#/components/schemas/WarehouseRequestId' },
      note: { type: 'string', maxLength: 500 },
    },
  },
  ApiResponse: {
    type: 'object',
    required: ['success'],
    properties: {
      success: { type: 'boolean' },
      data: {},
      message: { type: 'string' },
      errorCode: { type: 'string' },
      timestamp: { type: 'string', format: 'date-time' },
      meta: { $ref: '#/components/schemas/PaginationMeta' },
    },
  },
  ErrorResponse: {
    type: 'object',
    required: ['success', 'message', 'errorCode', 'timestamp', 'path'],
    properties: {
      success: { type: 'boolean', example: false },
      message: { type: 'string' },
      errorCode: { type: 'string' },
      timestamp: { type: 'string', format: 'date-time' },
      path: { type: 'string' },
    },
  },
};
