export const openApiSchemas = {
  PaginationMeta: {
    type: 'object',
    properties: {
      page: { type: 'integer', minimum: 1 },
      pageSize: { type: 'integer', minimum: 1, maximum: 100 },
      total: { type: 'integer', minimum: 0 },
      totalPages: { type: 'integer', minimum: 0 },
    },
  },
  CustomerListItem: {
    type: 'object',
    required: ['id', 'name', 'status', 'riskLevel'],
    properties: {
      id: { type: 'integer' },
      name: { type: 'string' },
      displayName: { type: 'string', nullable: true },
      nameZh: { type: 'string', nullable: true },
      nameEn: { type: 'string', nullable: true },
      nameVi: { type: 'string', nullable: true },
      contactName: { type: 'string', nullable: true },
      contactPhone: { type: 'string', nullable: true },
      contactEmail: { type: 'string', nullable: true },
      segment: { type: 'string', nullable: true, enum: ['direct', 'channel', 'mixed', null] },
      status: { type: 'string' },
      riskLevel: { type: 'string' },
      poolState: { type: 'string', nullable: true },
      salespersonId: { type: 'integer', nullable: true },
      creditLimit: { type: 'number', nullable: true },
      overdueAmount: { type: 'number', nullable: true },
      statistics: { type: 'object', additionalProperties: true },
    },
  },
  CustomerListResponse: {
    allOf: [
      { $ref: '#/components/schemas/ApiResponse' },
      {
        type: 'object',
        properties: {
          data: { type: 'array', items: { $ref: '#/components/schemas/CustomerListItem' } },
          meta: { $ref: '#/components/schemas/PaginationMeta' },
        },
      },
    ],
  },
  OrderListItem: {
    type: 'object',
    required: ['id', 'orderNo', 'customerId', 'customerName', 'status', 'paymentStatus'],
    properties: {
      id: { type: 'integer' },
      orderNo: { type: 'string' },
      customerId: { type: 'integer' },
      customerName: { type: 'string' },
      customerNameZh: { type: 'string', nullable: true },
      customerNameEn: { type: 'string', nullable: true },
      customerNameVi: { type: 'string', nullable: true },
      status: { type: 'string' },
      paymentStatus: { type: 'string' },
      financialStatus: { type: 'string', nullable: true },
      fulfillmentStatus: { type: 'string', nullable: true },
      finalAmount: { type: 'number' },
      paidAmount: { type: 'number' },
      outstandingAmount: { type: 'number' },
      currency: { type: 'string' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
  },
  OrderListResponse: {
    allOf: [
      { $ref: '#/components/schemas/ApiResponse' },
      {
        type: 'object',
        properties: {
          data: { type: 'array', items: { $ref: '#/components/schemas/OrderListItem' } },
          meta: { $ref: '#/components/schemas/PaginationMeta' },
        },
      },
    ],
  },
  CollectionOverdueListItem: {
    type: 'object',
    required: ['orderId', 'orderNo', 'customerId', 'customerName', 'dueDate', 'daysOverdue', 'outstanding', 'paymentStatus', 'level', 'label', 'nextAction'],
    properties: {
      orderId: { type: 'integer' },
      orderNo: { type: 'string' },
      dueDate: { type: 'string', format: 'date-time' },
      daysOverdue: { type: 'integer', minimum: 0 },
      level: { type: 'integer', minimum: 1 },
      label: { type: 'string' },
      nextAction: { type: 'string' },
      channel: { type: 'string' },
      holdRecommended: { type: 'boolean' },
      outstanding: { type: 'number' },
      finalAmount: { type: 'number' },
      paidAmount: { type: 'number' },
      receivableAdjustmentAmount: { type: 'number' },
      paymentStatus: { type: 'string' },
      customerId: { type: 'integer' },
      customerName: { type: 'string' },
      customerNameZh: { type: 'string', nullable: true },
      customerNameEn: { type: 'string', nullable: true },
      customerNameVi: { type: 'string', nullable: true },
      customerDisplayName: { type: 'string', nullable: true },
      contactName: { type: 'string', nullable: true },
      contactPhone: { type: 'string', nullable: true },
      ownerName: { type: 'string' },
      riskLevel: { type: 'string' },
      overdueAmount: { type: 'number' },
      collectionsStatus: { type: 'string' },
      dunningLevel: { type: 'integer', minimum: 0 },
      nextActionAt: { type: 'string', format: 'date-time', nullable: true },
      reminderCount: { type: 'integer', minimum: 0 },
      lastReminderAt: { type: 'string', format: 'date-time', nullable: true },
      contractNo: { type: 'string', nullable: true },
      contractTitle: { type: 'string', nullable: true },
    },
  },
  CollectionOverdueListResponse: {
    allOf: [
      { $ref: '#/components/schemas/ApiResponse' },
      {
        type: 'object',
        properties: {
          data: { type: 'array', items: { $ref: '#/components/schemas/CollectionOverdueListItem' } },
          meta: { $ref: '#/components/schemas/PaginationMeta' },
        },
      },
    ],
  },
  AIAssistRequest: {
    type: 'object',
    additionalProperties: false,
    required: ['prompt'],
    properties: {
      prompt: { type: 'string', minLength: 1, maxLength: 2000 },
      language: { type: 'string', enum: ['zh-CN', 'en-US', 'vi-VN'] },
      currentPage: { type: 'string', maxLength: 120 },
      visibleCounts: {
        type: 'object',
        deprecated: true,
        description: 'Compatibility-only client hint. The server ignores this field and never forwards it to an external AI provider.',
        additionalProperties: { type: 'integer', minimum: 0, maximum: 1000000 },
      },
    },
  },
  AIAssistResponse: {
    allOf: [
      { $ref: '#/components/schemas/ApiResponse' },
      {
        type: 'object',
        properties: {
          data: {
            type: 'object',
            required: ['answer', 'mode'],
            properties: {
              answer: { type: 'string', maxLength: 4000 },
              mode: { type: 'string', enum: ['local', 'external'] },
              reason: { type: 'string', enum: ['disabled', 'sensitive', 'unconfigured', 'provider_error', 'audit_unavailable', 'unsafe_output', 'response_too_large', 'budget_unconfigured', 'budget_store_unavailable', 'budget_exhausted', 'circuit_open'] },
            },
          },
        },
      },
    ],
  },
  WarehouseRequestId: {
    type: 'string',
    minLength: 1,
    maxLength: 80,
    pattern: '^[A-Za-z0-9][A-Za-z0-9._:-]{0,79}$',
    description: 'Caller-generated idempotency key. An exact retry is accepted; reuse with a different payload is rejected.',
  },
  WarehouseStockAdjustmentRequest: {
    type: 'object',
    additionalProperties: false,
    required: ['quantity', 'expectedQuantity', 'requestId'],
    properties: {
      quantity: { type: 'number', minimum: 0, description: 'Requested absolute quantity after adjustment.' },
      expectedQuantity: { type: 'number', minimum: 0, description: 'Quantity last read by the caller. A stale value returns HTTP 409.' },
      requestId: { $ref: '#/components/schemas/WarehouseRequestId' },
      note: { type: 'string', maxLength: 500 },
    },
  },
  WarehouseStockTransferRequest: {
    type: 'object',
    additionalProperties: false,
    required: ['toLocationId', 'quantity', 'requestId'],
    properties: {
      toLocationId: { type: 'integer', minimum: 1 },
      quantity: { type: 'number', exclusiveMinimum: 0 },
      requestId: { $ref: '#/components/schemas/WarehouseRequestId' },
      note: { type: 'string', maxLength: 500 },
    },
  },
  WarehouseStockCreateRequest: {
    type: 'object',
    additionalProperties: true,
    required: ['locationId', 'productName', 'batchNo', 'quantity', 'sourceRef', 'reason'],
    properties: {
      locationId: { type: 'integer', minimum: 1 },
      materialId: { type: 'integer', minimum: 1, nullable: true, description: 'Canonical active material identity. When supplied, productName and unit are locked to master data.' },
      productName: { type: 'string', minLength: 1 },
      batchNo: { type: 'string', minLength: 1 },
      quantity: { type: 'number', exclusiveMinimum: 0 },
      unit: { type: 'string', minLength: 1 },
      sourceRef: { type: 'string', minLength: 1 },
      reason: { type: 'string', minLength: 1 },
      note: { type: 'string', nullable: true },
      unitCost: { type: 'number', minimum: 0, nullable: true },
      costAmountDelta: { type: 'number', nullable: true },
    },
  },
  ProcurementPurchaseOrderCreateRequest: {
    type: 'object',
    additionalProperties: true,
    required: ['supplierId', 'item', 'quantity', 'unit', 'price', 'eta'],
    properties: {
      supplierId: { type: 'integer', minimum: 1 },
      materialId: {
        type: 'integer',
        minimum: 1,
        nullable: true,
        description: 'Canonical material identity. When provided, the backend locks item and unit to active governed master data.',
      },
      item: { type: 'string', minLength: 1, description: 'Legacy-compatible display name; canonicalized when materialId is provided.' },
      quantity: { type: 'number', exclusiveMinimum: 0 },
      unit: { type: 'string', minLength: 1, description: 'Must equal the material base unit when materialId is provided.' },
      price: { type: 'number', minimum: 0 },
      currency: { type: 'string', minLength: 1, maxLength: 8 },
      exchangeRate: { type: 'number', exclusiveMinimum: 0 },
      taxRate: { type: 'number', minimum: 0 },
      taxAmount: { type: 'number', minimum: 0 },
      freightCost: { type: 'number', minimum: 0 },
      dutyCost: { type: 'number', minimum: 0 },
      insuranceCost: { type: 'number', minimum: 0 },
      otherCost: { type: 'number', minimum: 0 },
      eta: { type: 'string', minLength: 1 },
      status: { type: 'string' },
      salesOrderRef: { type: 'string' },
      salesOrderId: { type: 'integer', minimum: 1, nullable: true },
      isB2B: { type: 'boolean' },
    },
  },
  ProductionBomItemRequest: {
    type: 'object',
    additionalProperties: false,
    required: ['quantityPerUnit', 'unit'],
    anyOf: [
      { required: ['materialId'] },
      { required: ['materialName'] },
      { required: ['materialCode'] },
    ],
    properties: {
      materialId: { type: 'integer', minimum: 1, nullable: true },
      materialName: { type: 'string', nullable: true },
      materialCode: { type: 'string', nullable: true },
      ingredientRole: { type: 'string', nullable: true },
      dosageMode: { type: 'string', nullable: true },
      percentage: { type: 'number', minimum: 0, maximum: 100, nullable: true },
      quantityPerUnit: { type: 'number', exclusiveMinimum: 0 },
      unit: { type: 'string', minLength: 1 },
      lossRate: { type: 'number', minimum: 0, nullable: true },
      allowedVarianceRate: { type: 'number', minimum: 0, maximum: 100, nullable: true },
      processStage: { type: 'string', nullable: true },
      substituteGroup: { type: 'string', nullable: true },
      yieldContribution: { type: 'number', minimum: 0, maximum: 100, nullable: true },
      notes: { type: 'string', nullable: true },
    },
  },
  MaterialAlias: {
    type: 'object',
    required: ['id', 'alias', 'normalizedAlias', 'language', 'aliasType'],
    properties: {
      id: { type: 'integer', minimum: 1 },
      alias: { type: 'string' },
      normalizedAlias: { type: 'string' },
      language: { type: 'string', enum: ['zh', 'en', 'vi', 'und'] },
      aliasType: { type: 'string', enum: ['business', 'supplier', 'customer', 'legacy', 'translation'] },
    },
  },
  Material: {
    type: 'object',
    required: ['id', 'code', 'nameZh', 'category', 'baseUnit', 'status', 'isTemporary', 'updatedAt'],
    properties: {
      id: { type: 'integer', minimum: 1 },
      code: { type: 'string' },
      nameZh: { type: 'string' },
      nameEn: { type: 'string', nullable: true },
      nameVi: { type: 'string', nullable: true },
      category: { type: 'string', enum: ['raw_material', 'finished_good', 'semi_finished', 'packaging', 'consumable', 'service'] },
      baseUnit: { type: 'string' },
      specification: { type: 'string', nullable: true },
      status: { type: 'string', enum: ['draft', 'active', 'blocked', 'retired'] },
      isTemporary: { type: 'boolean' },
      casNumber: { type: 'string', nullable: true },
      unNumber: { type: 'string', nullable: true },
      hsCode: { type: 'string', nullable: true },
      shelfLifeDays: { type: 'integer', minimum: 1, maximum: 3650, nullable: true },
      complianceNotes: { type: 'string', nullable: true },
      aliases: { type: 'array', items: { $ref: '#/components/schemas/MaterialAlias' } },
      updatedAt: { type: 'string', format: 'date-time' },
    },
  },
  MaterialWriteRequest: {
    type: 'object',
    additionalProperties: false,
    required: ['code', 'nameZh', 'baseUnit'],
    properties: {
      code: { type: 'string', minLength: 2, maxLength: 64, pattern: '^[A-Za-z0-9][A-Za-z0-9._/-]*$' },
      nameZh: { type: 'string', minLength: 1, maxLength: 160 },
      nameEn: { type: 'string', nullable: true, maxLength: 160 },
      nameVi: { type: 'string', nullable: true, maxLength: 160 },
      category: { type: 'string', enum: ['raw_material', 'finished_good', 'semi_finished', 'packaging', 'consumable', 'service'] },
      baseUnit: { type: 'string', minLength: 1, maxLength: 24 },
      specification: { type: 'string', nullable: true, maxLength: 240 },
      status: { type: 'string', enum: ['draft', 'active', 'blocked', 'retired'] },
      isTemporary: { type: 'boolean' },
      casNumber: { type: 'string', nullable: true, maxLength: 64 },
      unNumber: { type: 'string', nullable: true, maxLength: 64 },
      hsCode: { type: 'string', nullable: true, maxLength: 64 },
      shelfLifeDays: { type: 'integer', minimum: 1, maximum: 3650, nullable: true },
      complianceNotes: { type: 'string', nullable: true, maxLength: 2000 },
    },
  },
  MaterialUpdateRequest: {
    type: 'object',
    additionalProperties: false,
    minProperties: 1,
    properties: {
      nameZh: { type: 'string', minLength: 1, maxLength: 160 },
      nameEn: { type: 'string', nullable: true, maxLength: 160 },
      nameVi: { type: 'string', nullable: true, maxLength: 160 },
      category: { type: 'string', enum: ['raw_material', 'finished_good', 'semi_finished', 'packaging', 'consumable', 'service'] },
      baseUnit: { type: 'string', minLength: 1, maxLength: 24 },
      specification: { type: 'string', nullable: true, maxLength: 240 },
      status: { type: 'string', enum: ['draft', 'active', 'blocked', 'retired'] },
      isTemporary: { type: 'boolean' },
      casNumber: { type: 'string', nullable: true, maxLength: 64 },
      unNumber: { type: 'string', nullable: true, maxLength: 64 },
      hsCode: { type: 'string', nullable: true, maxLength: 64 },
      shelfLifeDays: { type: 'integer', minimum: 1, maximum: 3650, nullable: true },
      complianceNotes: { type: 'string', nullable: true, maxLength: 2000 },
      expectedUpdatedAt: { type: 'string', format: 'date-time' },
    },
  },
  MaterialBomBackfillSource: {
    type: 'object',
    additionalProperties: false,
    required: ['materialName', 'materialCode', 'unit'],
    properties: {
      materialName: { type: 'string', minLength: 1, maxLength: 160 },
      materialCode: { type: 'string', nullable: true, maxLength: 64 },
      unit: { type: 'string', minLength: 1, maxLength: 24 },
    },
  },
  MaterialBomBackfillMapping: {
    type: 'object',
    additionalProperties: false,
    required: ['source', 'materialId', 'expectedCount', 'expectedFingerprint'],
    properties: {
      source: { $ref: '#/components/schemas/MaterialBomBackfillSource' },
      materialId: { type: 'integer', minimum: 1 },
      expectedCount: { type: 'integer', minimum: 1, maximum: 500 },
      expectedFingerprint: { type: 'string', pattern: '^[a-f0-9]{64}$' },
    },
  },
  MaterialBomBackfillRequest: {
    type: 'object',
    additionalProperties: false,
    required: ['mappings'],
    properties: {
      mappings: {
        type: 'array',
        minItems: 1,
        maxItems: 50,
        items: { $ref: '#/components/schemas/MaterialBomBackfillMapping' },
      },
    },
  },
  ProductionBomCreateRequest: {
    type: 'object',
    additionalProperties: false,
    required: ['productName', 'outputUnit', 'shelfLifeDays', 'items'],
    properties: {
      materialId: {
        type: 'integer',
        minimum: 1,
        nullable: true,
        description: 'Canonical finished-good or semi-finished material. Required when status is not draft.',
      },
      productName: { type: 'string', minLength: 1 },
      version: { type: 'string', nullable: true },
      bomType: { type: 'string', nullable: true },
      status: { type: 'string', nullable: true },
      formulationMode: { type: 'string', nullable: true },
      outputUnit: { type: 'string', minLength: 1 },
      shelfLifeDays: {
        type: 'integer',
        minimum: 1,
        maximum: 3650,
        description: 'Required finished-product shelf-life policy. Completion fails closed when a legacy BOM has no valid value.',
      },
      standardBatchSize: { type: 'number', exclusiveMinimum: 0, nullable: true },
      batchSizeUnit: { type: 'string', nullable: true },
      density: { type: 'number', exclusiveMinimum: 0, nullable: true },
      solidContent: { type: 'number', minimum: 0, maximum: 100, nullable: true },
      effectiveFrom: { type: 'string', format: 'date-time', nullable: true },
      effectiveTo: { type: 'string', format: 'date-time', nullable: true },
      processJson: { type: 'string', nullable: true },
      qualitySpecJson: { type: 'string', nullable: true },
      notes: { type: 'string', nullable: true },
      items: {
        type: 'array',
        minItems: 1,
        items: { $ref: '#/components/schemas/ProductionBomItemRequest' },
      },
    },
  },
  ShipmentCreateRequest: {
    type: 'object',
    additionalProperties: true,
    required: ['customerId', 'productName', 'quantity'],
    properties: {
      customerId: { type: 'integer', minimum: 1 },
      orderId: { type: 'integer', minimum: 1, nullable: true },
      orderItemId: { type: 'integer', minimum: 1, nullable: true, description: 'Exact sales-order line. The backend rejects cross-order, cross-customer, and cross-material substitution.' },
      materialId: { type: 'integer', minimum: 1, nullable: true, description: 'Canonical shipped material. Must match orderItemId when both are supplied.' },
      productName: { type: 'string', minLength: 1, description: 'Legacy-compatible display name; canonicalized when materialId or orderItemId is supplied.' },
      quantity: { type: 'number', exclusiveMinimum: 0 },
      unit: { type: 'string', minLength: 1 },
      batchNo: { type: 'string', nullable: true, description: 'Must identify a product batch with the same canonical material.' },
      packageType: { type: 'string', nullable: true },
      carrier: { type: 'string', nullable: true },
      trackingNo: { type: 'string', nullable: true },
    },
  },
  ApiResponse: {
    type: 'object',
    required: ['success'],
    properties: {
      success: { type: 'boolean' },
      data: {},
      message: { type: 'string' },
      errorCode: { type: 'string' },
      timestamp: { type: 'string', format: 'date-time' },
      meta: { $ref: '#/components/schemas/PaginationMeta' },
    },
  },
  ErrorResponse: {
    type: 'object',
    required: ['success', 'message', 'errorCode', 'timestamp', 'path'],
    properties: {
      success: { type: 'boolean', example: false },
      message: { type: 'string' },
      errorCode: { type: 'string' },
      timestamp: { type: 'string', format: 'date-time' },
      path: { type: 'string' },
    },
  },
};
