jest.mock('../config/database',()=>({__esModule:true,default:{$transaction:jest.fn()}}));
import prisma from '../config/database';
import { MaterialPackagingService } from './material-packaging.service';

function fixture(patch: Record<string,unknown> = {}) {
  const r={id:2,materialId:9,createdBy:5,status:'draft',packageUnit:'桶',updatedAt:new Date('2026-09-29T00:00:00Z'),...patch};
  const tx={$executeRaw:jest.fn().mockResolvedValue(1),material:{findUnique:jest.fn().mockResolvedValue({id:9,status:'active',isTemporary:false,category:'finished_good',baseUnit:'桶'})},materialPackagingRevision:{findUnique:jest.fn().mockResolvedValue(r),updateMany:jest.fn().mockResolvedValue({count:1}),findUniqueOrThrow:jest.fn().mockResolvedValue(r)},auditLog:{create:jest.fn()}};
  (prisma.$transaction as jest.Mock).mockImplementation(f=>f(tx));return {r,tx};
}
describe('packaging independent approval and immutable net mass',()=>{
  it('rejects self approval even for an authorized caller',async()=>{const {r,tx}=fixture();await expect(MaterialPackagingService.transition(9,2,'approved',r.updatedAt.toISOString(),'verified',5)).rejects.toThrow('INDEPENDENT_REVIEW_REQUIRED');expect(tx.materialPackagingRevision.updateMany).not.toHaveBeenCalled();expect(tx.auditLog.create).not.toHaveBeenCalled();});
  it('locks before read and approves once with a version CAS',async()=>{const {r,tx}=fixture();await MaterialPackagingService.transition(9,2,'approved',r.updatedAt.toISOString(),'verified',7);expect(tx.$executeRaw.mock.invocationCallOrder[0]).toBeLessThan(tx.materialPackagingRevision.findUnique.mock.invocationCallOrder[0]);const {where,data}=tx.materialPackagingRevision.updateMany.mock.calls[0][0];expect(where).toEqual({id:2,status:'draft',updatedAt:r.updatedAt});expect(data).toMatchObject({status:'approved',approvedBy:7});expect(data.netMass).toBeUndefined();expect(data.sourceReference).toBeUndefined();expect(tx.auditLog.create).toHaveBeenCalledTimes(1);});
  it.each([{status:'approved'},{status:'retired'}])('does not approve again: %j',async patch=>{const {r,tx}=fixture(patch);await expect(MaterialPackagingService.transition(9,2,'approved',r.updatedAt.toISOString(),'again',7)).rejects.toThrow('STATE_INVALID');expect(tx.auditLog.create).not.toHaveBeenCalled();});
  it('rejects stale, cross-material and failed CAS updates without audit',async()=>{const {r,tx}=fixture();await expect(MaterialPackagingService.transition(10,2,'approved',r.updatedAt.toISOString(),'x',7)).rejects.toThrow('NOT_FOUND');await expect(MaterialPackagingService.transition(9,2,'approved','2025-01-01T00:00:00Z','x',7)).rejects.toThrow('CONCURRENT_UPDATE');tx.materialPackagingRevision.updateMany.mockResolvedValue({count:0});await expect(MaterialPackagingService.transition(9,2,'approved',r.updatedAt.toISOString(),'x',7)).rejects.toThrow('CONCURRENT_UPDATE');expect(tx.auditLog.create).not.toHaveBeenCalled();});
  it('retirement changes lifecycle only, retaining original approval provenance',async()=>{const {r,tx}=fixture({status:'approved'});await MaterialPackagingService.transition(9,2,'retired',r.updatedAt.toISOString(),'superseded',7);const {data}=tx.materialPackagingRevision.updateMany.mock.calls[0][0];expect(data).toMatchObject({status:'retired',retiredBy:7,retireReason:'superseded'});expect(data.approvedBy).toBeUndefined();expect(data.netMass).toBeUndefined();});
});
