// Generated by scripts/generate-api-sdk-v1.cjs. Do not edit by hand.
// Source: backend/src/routes/apiRegistry.ts (24 modules).

export type AilaoDaApiNamespace = '/api' | '/api/v1';

export type AilaoDaPaginationMeta = {
  page?: number;
  pageSize?: number;
  total?: number;
  totalPages?: number;
};

export type AilaoDaApiResponse<T = unknown> = {
  success: boolean;
  data?: T;
  message?: string;
  errorCode?: string;
  timestamp?: string;
  meta?: AilaoDaPaginationMeta;
};

export type AilaoDaQueryPrimitive = string | number | boolean | null | undefined;

export type AilaoDaListQuery = {
  [key: string]: AilaoDaQueryPrimitive;
  page?: number;
  pageSize?: number;
  search?: string;
  sortBy?: string;
  sortOrder?: "asc" | "desc";
};

export type AilaoDaCustomerListQuery = AilaoDaListQuery & {
  status?: string;
  riskLevel?: "low" | "medium" | "high";
  segment?: "direct" | "channel" | "mixed";
  poolState?: "public" | "internal" | "private";
  viewMode?: "public" | "my";
  salespersonId?: number | string;
};

export type AilaoDaCustomerListItem = {
  id: number | string;
  name?: string;
  displayName?: string | null;
  nameZh?: string | null;
  nameEn?: string | null;
  nameVi?: string | null;
  contactName?: string | null;
  contactPhone?: string | null;
  contactEmail?: string | null;
  segment?: "direct" | "channel" | "mixed" | string | null;
  status?: string;
  riskLevel?: string;
  poolState?: string | null;
  salespersonId?: number | string | null;
  creditLimit?: number | null;
  overdueAmount?: number | null;
  statistics?: Record<string, unknown>;
};

export type AilaoDaCustomerListResponse = AilaoDaApiResponse<AilaoDaCustomerListItem[]>;

export type AilaoDaOrderListQuery = AilaoDaListQuery & {
  status?: string;
  customerId?: number | string;
  startDate?: string;
  endDate?: string;
};

export type AilaoDaOrderListItem = {
  id: number | string;
  orderNo: string;
  customerId?: number | string;
  customerName?: string;
  customerNameZh?: string | null;
  customerNameEn?: string | null;
  customerNameVi?: string | null;
  status?: string;
  paymentStatus?: string;
  financialStatus?: string | null;
  fulfillmentStatus?: string | null;
  finalAmount?: number;
  paidAmount?: number;
  outstandingAmount?: number;
  currency?: string;
  createdAt?: string;
  updatedAt?: string;
};

export type AilaoDaOrderListResponse = AilaoDaApiResponse<AilaoDaOrderListItem[]>;

export type AilaoDaCollectionOverdueListQuery = AilaoDaListQuery & {
  search?: string;
};

export type AilaoDaCollectionOverdueListItem = {
  orderId: number | string;
  orderNo: string;
  dueDate: string;
  daysOverdue: number;
  level: number;
  label: string;
  nextAction: string;
  channel?: string;
  holdRecommended?: boolean;
  outstanding: number;
  finalAmount?: number;
  paidAmount?: number;
  receivableAdjustmentAmount?: number;
  paymentStatus: string;
  customerId: number | string;
  customerName: string;
  customerNameZh?: string | null;
  customerNameEn?: string | null;
  customerNameVi?: string | null;
  customerDisplayName?: string | null;
  contactName?: string | null;
  contactPhone?: string | null;
  ownerName?: string;
  riskLevel?: string;
  overdueAmount?: number;
  collectionsStatus?: string;
  dunningLevel?: number;
  nextActionAt?: string | null;
  reminderCount?: number;
  lastReminderAt?: string | null;
  contractNo?: string | null;
  contractTitle?: string | null;
};

export type AilaoDaCollectionOverdueListResponse = AilaoDaApiResponse<AilaoDaCollectionOverdueListItem[]>;

export const AILAO_DA_API_MODULES = [
  { path: '/auth', tag: 'Auth', requiresAuth: false, summary: 'Authentication, session, and password endpoints.' },
  { path: '/customers', tag: 'Customers', requiresAuth: true, summary: 'CRM customer records, pool governance, import, export, and customer activity.' },
  { path: '/orders', tag: 'Orders', requiresAuth: true, summary: 'Sales order workspace, payment, fulfillment, and order lifecycle operations.' },
  { path: '/samples', tag: 'Samples', requiresAuth: true, summary: 'Sample request and sample tracking workflows.' },
  { path: '/shipping', tag: 'Shipping', requiresAuth: true, summary: 'Shipping plans, receipts, logistics, and shipment state transitions.' },
  { path: '/rma', tag: 'RMA', requiresAuth: true, summary: 'Return merchandise authorization and after-sales workflows.' },
  { path: '/team', tag: 'Team', requiresAuth: true, summary: 'Team account lifecycle, role assignment, and operator administration.' },
  { path: '/dashboard', tag: 'Dashboard', requiresAuth: true, summary: 'Executive dashboard and operational summary read models.' },
  { path: '/assets', tag: 'Assets', requiresAuth: true, summary: 'Asset records and customer asset movement history.' },
  { path: '/audit', tag: 'Audit', requiresAuth: true, summary: 'Audit event query and governance trail endpoints.' },
  { path: '/procurement', tag: 'Procurement', requiresAuth: true, summary: 'Supplier, purchase order, receipt, and procurement lifecycle operations.' },
  { path: '/collections', tag: 'Collections', requiresAuth: true, summary: 'Receivables, overdue collection, promise-to-pay, and credit-hold workflows.' },
  { path: '/adjustments', tag: 'Adjustments', requiresAuth: true, summary: 'Inventory and finance adjustment workflows with approval boundaries.' },
  { path: '/system', tag: 'System', requiresAuth: true, summary: 'System administration, backup, restore, and runtime governance operations.' },
  { path: '/barter', tag: 'Barter', requiresAuth: true, summary: 'Barter agreement, counterparty, stock, and settlement workflows.' },
  { path: '/timber', tag: 'Timber', requiresAuth: true, summary: 'Timber-specific legacy-compatible trade workflows.' },
  { path: '/contracts', tag: 'Contracts', requiresAuth: true, summary: 'Contract records and contract lifecycle operations.' },
  { path: '/production', tag: 'Production', requiresAuth: true, summary: 'Chemical BOM, production order, completion, and cost ledger workflows.' },
  { path: '/finance', tag: 'Finance', requiresAuth: true, summary: 'Finance reports, summaries, and account reconciliation endpoints.' },
  { path: '/currency', tag: 'Currency', requiresAuth: true, summary: 'Currency rate lookup and cache-backed exchange-rate operations.' },
  { path: '/warehouses', tag: 'Warehouses', requiresAuth: true, summary: 'Warehouse, stock ledger, and stock transfer operations.' },
  { path: '/receipt-discrepancies', tag: 'Receipt Discrepancies', requiresAuth: true, summary: 'Receipt discrepancy review, tolerance, and resolution operations.' },
  { path: '/roles', tag: 'Roles', requiresAuth: true, summary: 'Role permissions, role audit diffs, and authorization policy endpoints.' },
  { path: '/commercial', tag: 'Commercial Platform', requiresAuth: true, summary: 'Commercial platform readiness, workflow, BI, alert, and notification APIs.' },
] as const;

export type AilaoDaApiModule = typeof AILAO_DA_API_MODULES[number];
export type AilaoDaApiModulePath = AilaoDaApiModule["path"];

