// Generated by scripts/generate-api-sdk-v1.cjs. Do not edit by hand.
// Source: backend/src/routes/apiRegistry.ts (25 modules).

import { AILAO_DA_API_MODULES, type AilaoDaApiModulePath, type AilaoDaApiNamespace, type AilaoDaApiResponse, type AilaoDaCollectionOverdueListItem, type AilaoDaCollectionOverdueListQuery, type AilaoDaCollectionOverdueListResponse, type AilaoDaCustomerListItem, type AilaoDaCustomerListQuery, type AilaoDaCustomerListResponse, type AilaoDaOrderImportResponse, type AilaoDaOrderImportRow, type AilaoDaOrderListItem, type AilaoDaOrderListQuery, type AilaoDaOrderListResponse } from '../shared/api-contract';

export { AILAO_DA_API_MODULES, type AilaoDaApiModulePath, type AilaoDaApiNamespace, type AilaoDaApiResponse, type AilaoDaCollectionOverdueListItem, type AilaoDaCollectionOverdueListQuery, type AilaoDaCollectionOverdueListResponse, type AilaoDaCustomerListItem, type AilaoDaCustomerListQuery, type AilaoDaCustomerListResponse, type AilaoDaOrderImportItem, type AilaoDaOrderImportResponse, type AilaoDaOrderImportResult, type AilaoDaOrderImportRow, type AilaoDaOrderListItem, type AilaoDaOrderListQuery, type AilaoDaOrderListResponse } from "../shared/api-contract";

export type AilaoDaRequestOptions = {
  token?: string;
  query?: Record<string, string | number | boolean | null | undefined>;
  body?: unknown;
  signal?: AbortSignal;
  headers?: Record<string, string>;
};

export type AilaoDaTypedRequestOptions<TQuery extends AilaoDaRequestOptions["query"] = AilaoDaRequestOptions["query"]> = Omit<AilaoDaRequestOptions, "query"> & {
  query?: TQuery;
};

export type AilaoDaClientOptions = {
  baseUrl?: string;
  namespace?: AilaoDaApiNamespace;
  token?: string | (() => string | undefined);
  fetchImpl?: typeof fetch;
};

const trimTrailingSlash = (value: string) => value.replace(/\/+$/, "");
const trimSlashes = (value: string) => value.replace(/^\/+|\/+$/g, "");

const buildQuery = (query?: AilaoDaRequestOptions["query"]) => {
  const params = new URLSearchParams();
  for (const [key, value] of Object.entries(query || {})) {
    if (value === undefined || value === null) continue;
    params.set(key, String(value));
  }
  const text = params.toString();
  return text ? `?${text}` : "";
};

export class AilaoDaApiError extends Error {
  status: number;
  errorCode?: string;
  body: unknown;

  constructor(status: number, body: unknown) {
    const record = body && typeof body === "object" ? body as Record<string, unknown> : {};
    super(String(record.message || `AilaoDa API request failed with status ${status}`));
    this.name = "AilaoDaApiError";
    this.status = status;
    this.errorCode = typeof record.errorCode === "string" ? record.errorCode : undefined;
    this.body = body;
  }
}

export class AilaoDaApiClient {
  private readonly baseUrl: string;
  private readonly namespace: AilaoDaApiNamespace;
  private readonly token?: string | (() => string | undefined);
  private readonly fetchImpl: typeof fetch;

  constructor(options: AilaoDaClientOptions = {}) {
    this.baseUrl = trimTrailingSlash(options.baseUrl || "");
    this.namespace = options.namespace || "/api/v1";
    this.token = options.token;
    this.fetchImpl = options.fetchImpl || fetch;
  }

  async request<T = unknown>(method: string, modulePath: AilaoDaApiModulePath | string, childPath = "", options: AilaoDaRequestOptions = {}): Promise<AilaoDaApiResponse<T>> {
    const resolvedToken = options.token ?? (typeof this.token === "function" ? this.token() : this.token);
    const headers: Record<string, string> = { Accept: "application/json", ...options.headers };
    let body: BodyInit | undefined;
    if (options.body !== undefined) {
      headers["Content-Type"] = headers["Content-Type"] || "application/json";
      body = typeof options.body === "string" ? options.body : JSON.stringify(options.body);
    }
    if (resolvedToken) headers.Authorization = `Bearer ${resolvedToken}`;

    const url = `${this.baseUrl}${this.namespace}${modulePath}${childPath ? `/${trimSlashes(childPath)}` : ""}${buildQuery(options.query)}`;
    const response = await this.fetchImpl(url, { method, headers, body, signal: options.signal });
    const contentType = response.headers.get("content-type") || "";
    const payload = contentType.includes("application/json") ? await response.json() : await response.text();
    if (!response.ok) throw new AilaoDaApiError(response.status, payload);
    return payload as AilaoDaApiResponse<T>;
  }

  get<T = unknown>(modulePath: AilaoDaApiModulePath | string, options?: AilaoDaRequestOptions) { return this.request<T>("GET", modulePath, "", options); }
  post<T = unknown>(modulePath: AilaoDaApiModulePath | string, options?: AilaoDaRequestOptions) { return this.request<T>("POST", modulePath, "", options); }
  put<T = unknown>(modulePath: AilaoDaApiModulePath | string, options?: AilaoDaRequestOptions) { return this.request<T>("PUT", modulePath, "", options); }
  patch<T = unknown>(modulePath: AilaoDaApiModulePath | string, options?: AilaoDaRequestOptions) { return this.request<T>("PATCH", modulePath, "", options); }
  delete<T = unknown>(modulePath: AilaoDaApiModulePath | string, options?: AilaoDaRequestOptions) { return this.request<T>("DELETE", modulePath, "", options); }

  listCustomers(options: AilaoDaTypedRequestOptions<AilaoDaCustomerListQuery> = {}): Promise<AilaoDaCustomerListResponse> {
    return this.request<AilaoDaCustomerListItem[]>("GET", "/customers", "", options);
  }

  listOrders(options: AilaoDaTypedRequestOptions<AilaoDaOrderListQuery> = {}): Promise<AilaoDaOrderListResponse> {
    return this.request<AilaoDaOrderListItem[]>("GET", "/orders", "", options);
  }

  importOrders(orders: AilaoDaOrderImportRow[], idempotencyKey: string, options: Omit<AilaoDaRequestOptions, "body"> = {}): Promise<AilaoDaOrderImportResponse> {
    return this.request("POST", "/orders", "import", {
      ...options,
      headers: { ...options.headers, "Idempotency-Key": idempotencyKey },
      body: { orders },
    });
  }

  listCollectionOverdueOrders(options: AilaoDaTypedRequestOptions<AilaoDaCollectionOverdueListQuery> = {}): Promise<AilaoDaCollectionOverdueListResponse> {
    return this.request<AilaoDaCollectionOverdueListItem[]>("GET", "/collections", "overdue", options);
  }

  auth = {
    list: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("GET", "/auth", "", options),
    create: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("POST", "/auth", "", options),
    request: <T = unknown>(method: string, childPath = "", options?: AilaoDaRequestOptions) => this.request<T>(method, "/auth", childPath, options),
  };
  customers = {
    list: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("GET", "/customers", "", options),
    create: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("POST", "/customers", "", options),
    request: <T = unknown>(method: string, childPath = "", options?: AilaoDaRequestOptions) => this.request<T>(method, "/customers", childPath, options),
  };
  orders = {
    list: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("GET", "/orders", "", options),
    create: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("POST", "/orders", "", options),
    request: <T = unknown>(method: string, childPath = "", options?: AilaoDaRequestOptions) => this.request<T>(method, "/orders", childPath, options),
  };
  samples = {
    list: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("GET", "/samples", "", options),
    create: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("POST", "/samples", "", options),
    request: <T = unknown>(method: string, childPath = "", options?: AilaoDaRequestOptions) => this.request<T>(method, "/samples", childPath, options),
  };
  shipping = {
    list: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("GET", "/shipping", "", options),
    create: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("POST", "/shipping", "", options),
    request: <T = unknown>(method: string, childPath = "", options?: AilaoDaRequestOptions) => this.request<T>(method, "/shipping", childPath, options),
  };
  rma = {
    list: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("GET", "/rma", "", options),
    create: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("POST", "/rma", "", options),
    request: <T = unknown>(method: string, childPath = "", options?: AilaoDaRequestOptions) => this.request<T>(method, "/rma", childPath, options),
  };
  team = {
    list: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("GET", "/team", "", options),
    create: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("POST", "/team", "", options),
    request: <T = unknown>(method: string, childPath = "", options?: AilaoDaRequestOptions) => this.request<T>(method, "/team", childPath, options),
  };
  dashboard = {
    list: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("GET", "/dashboard", "", options),
    create: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("POST", "/dashboard", "", options),
    request: <T = unknown>(method: string, childPath = "", options?: AilaoDaRequestOptions) => this.request<T>(method, "/dashboard", childPath, options),
  };
  assets = {
    list: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("GET", "/assets", "", options),
    create: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("POST", "/assets", "", options),
    request: <T = unknown>(method: string, childPath = "", options?: AilaoDaRequestOptions) => this.request<T>(method, "/assets", childPath, options),
  };
  audit = {
    list: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("GET", "/audit", "", options),
    create: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("POST", "/audit", "", options),
    request: <T = unknown>(method: string, childPath = "", options?: AilaoDaRequestOptions) => this.request<T>(method, "/audit", childPath, options),
  };
  procurement = {
    list: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("GET", "/procurement", "", options),
    create: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("POST", "/procurement", "", options),
    request: <T = unknown>(method: string, childPath = "", options?: AilaoDaRequestOptions) => this.request<T>(method, "/procurement", childPath, options),
  };
  collections = {
    list: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("GET", "/collections", "", options),
    create: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("POST", "/collections", "", options),
    request: <T = unknown>(method: string, childPath = "", options?: AilaoDaRequestOptions) => this.request<T>(method, "/collections", childPath, options),
  };
  adjustments = {
    list: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("GET", "/adjustments", "", options),
    create: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("POST", "/adjustments", "", options),
    request: <T = unknown>(method: string, childPath = "", options?: AilaoDaRequestOptions) => this.request<T>(method, "/adjustments", childPath, options),
  };
  system = {
    list: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("GET", "/system", "", options),
    create: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("POST", "/system", "", options),
    request: <T = unknown>(method: string, childPath = "", options?: AilaoDaRequestOptions) => this.request<T>(method, "/system", childPath, options),
  };
  barter = {
    list: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("GET", "/barter", "", options),
    create: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("POST", "/barter", "", options),
    request: <T = unknown>(method: string, childPath = "", options?: AilaoDaRequestOptions) => this.request<T>(method, "/barter", childPath, options),
  };
  timber = {
    list: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("GET", "/timber", "", options),
    create: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("POST", "/timber", "", options),
    request: <T = unknown>(method: string, childPath = "", options?: AilaoDaRequestOptions) => this.request<T>(method, "/timber", childPath, options),
  };
  contracts = {
    list: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("GET", "/contracts", "", options),
    create: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("POST", "/contracts", "", options),
    request: <T = unknown>(method: string, childPath = "", options?: AilaoDaRequestOptions) => this.request<T>(method, "/contracts", childPath, options),
  };
  production = {
    list: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("GET", "/production", "", options),
    create: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("POST", "/production", "", options),
    request: <T = unknown>(method: string, childPath = "", options?: AilaoDaRequestOptions) => this.request<T>(method, "/production", childPath, options),
  };
  finance = {
    list: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("GET", "/finance", "", options),
    create: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("POST", "/finance", "", options),
    request: <T = unknown>(method: string, childPath = "", options?: AilaoDaRequestOptions) => this.request<T>(method, "/finance", childPath, options),
  };
  currency = {
    list: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("GET", "/currency", "", options),
    create: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("POST", "/currency", "", options),
    request: <T = unknown>(method: string, childPath = "", options?: AilaoDaRequestOptions) => this.request<T>(method, "/currency", childPath, options),
  };
  warehouses = {
    list: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("GET", "/warehouses", "", options),
    create: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("POST", "/warehouses", "", options),
    request: <T = unknown>(method: string, childPath = "", options?: AilaoDaRequestOptions) => this.request<T>(method, "/warehouses", childPath, options),
  };
  receiptDiscrepancies = {
    list: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("GET", "/receipt-discrepancies", "", options),
    create: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("POST", "/receipt-discrepancies", "", options),
    request: <T = unknown>(method: string, childPath = "", options?: AilaoDaRequestOptions) => this.request<T>(method, "/receipt-discrepancies", childPath, options),
  };
  roles = {
    list: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("GET", "/roles", "", options),
    create: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("POST", "/roles", "", options),
    request: <T = unknown>(method: string, childPath = "", options?: AilaoDaRequestOptions) => this.request<T>(method, "/roles", childPath, options),
  };
  commercialPlatform = {
    list: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("GET", "/commercial", "", options),
    create: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("POST", "/commercial", "", options),
    request: <T = unknown>(method: string, childPath = "", options?: AilaoDaRequestOptions) => this.request<T>(method, "/commercial", childPath, options),
  };
  ai = {
    list: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("GET", "/ai", "", options),
    create: <T = unknown>(options?: AilaoDaRequestOptions) => this.request<T>("POST", "/ai", "", options),
    request: <T = unknown>(method: string, childPath = "", options?: AilaoDaRequestOptions) => this.request<T>(method, "/ai", childPath, options),
  };
}

